name: Build and Test

on:
  push:
    branches:
      - main  # Chaque fois qu'on pousse sur la branche main
  pull_request:
    branches:
      - main  # Chaque fois qu'une PR est faite sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest  # L'environnement d'exécution

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Récupérer le code du repo

      - name: Set up JDK 11
        uses: actions/setup-java@v3  # Installer Java
        with:
          java-version: '11'  # Utilise JDK 11
          distribution: ''

      - name: Build with Maven
        run: mvn clean package  # Compiler le projet

  test:
    runs-on: ubuntu-latest  # L'environnement d'exécution

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: mvn test  # Lancer les tests unitaires
